let stockProductos = [
  {
    id: 1,
    nombre: "Bocaditos de Avena Arrollada",
    tipo: "extrusado",
    desc: "Bocaditos de cereales con avena",
    categoria: "almohaditas",
    precio: 180,
    img: "/img/Cereal-01.jpg",
    cantidad: 1,
  },
  {
    id: 2,
    nombre: "Bocaditos de Avellana",
    tipo: "extrusado",
    desc: "Bocaditos de cereales rellenos de avellana",
    categoria: "almohaditas",
    precio: 180,
    img: "/img/Cereal-02.jpg",
    cantidad: 1,
  },
  {
    id: 3,
    nombre: "Bocaditos de Frutilla",
    tipo: "extrusado",
    desc: "Bocaditos de cereales rellenos de frutilla",
    categoria: "almohaditas",
    precio: 180,
    img: "/img/Cereal-03.jpg",
    cantidad: 1,
  },
  {
    id: 4,
    nombre: "Bocaditos de Maní",
    tipo: "extrusado",
    desc: "Bocaditos de cereales rellenos de crema de maní",
    categoria: "almohaditas",
    precio: 180,
    img: "/img/Cereal-04.jpg",
    cantidad: 1,
  },
  {
    id: 5,
    nombre: "Bocaditos de Chocolate Blanco",
    tipo: "extrusado",
    desc: "Bocaditos de cereales rellenos de chocolate blanco",
    categoria: "almohaditas",
    precio: 180,
    img: "/img/Cereal-05.jpg",
    cantidad: 1,
  },
  {
    id: 6,
    nombre: "Bocaditos de Limón",
    tipo: "extrusado",
    desc: "Bocaditos de cereales rellenos de limón",
    categoria: "almohaditas",
    precio: 180,
    img: "/img/Cereal-06.jpg",
    cantidad: 1,
  },
  {
    id: 7,
    nombre: "Granola con Frutos Rojos",
    tipo: "tradicional",
    desc: "Mezcla de avena, crispines de arroz, maíz, coco, miel, ciruelas y frutillas deshidratadas",
    categoria: "granola",
    precio: 400,
    img: "/img/Cereal-07.jpg",
    cantidad: 1,
  },
  {
    id: 8,
    nombre: "Granola con Almendras y Pasas",
    tipo: "tradicional",
    desc: "Mezcla de avena, crispines de arroz, maíz, coco, miel, almendras y pasas de uva",
    categoria: "granola",
    precio: 400,
    img: "/img/Cereal-08.jpg",
    cantidad: 1,
  },
  {
    id: 9,
    nombre: "Bocaditos con Salvado",
    tipo: "extrusado",
    desc: "Bocaditos de cereales rellenos de 2 salvados",
    categoria: "almohaditas",
    precio: 180,
    img: "/img/Cereal-09.jpg",
    cantidad: 1,
  },
  {
    id: 10,
    nombre: "Fibra Total con Pasas",
    tipo: "extrusado",
    desc: "Cereal integral con pasas de uva",
    categoria: "integrales",
    precio: 200,
    img: "/img/Cereal-10.jpg",
    cantidad: 1,
  },
  {
    id: 11,
    nombre: "Copos de Maíz sin sal",
    tipo: "tradicional",
    desc: "Copos de maíz sin sal adicionada",
    categoria: "sin sal",
    precio: 700,
    img: "/img/Cereal-11.jpg",
    cantidad: 1,
  },
  {
    id: 12,
    nombre: "Copos de Maíz Tradicionales",
    tipo: "tradicional",
    desc: "Copos de maíz tradicionales",
    categoria: "clásico",
    precio: 700,
    img: "/img/Cereal-12.jpg",
    cantidad: 1,
  },
];

// const [e,f,g,h,i,,,,,,,,,,,,,,,,a,b,c,d] = stockProductos

// console.log(stockProductos[12]);

// console.log(a)
// console.log(b)
// console.log(c)
// console.log(d)
